feat: centralize configuration management under new 'dk config' command and enhance 'dk list'

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,2 +1,7 @@
-#!/usr/bin/env sh
 bunx lint-staged
+
+if [ $? -ne 0 ]; then
+  echo "Lint-staged failed! Aborting commit."
+  exit 1
+fi
+exit 0
